### ISSUE TITLE
漫畫人下載錯誤 SSLError

### ISSUE THREAD

**Issue by IthildinX** [eight04/ComicCrawler#226] opened 2019-11-03 05:04 UTC
https://www.manhuaren.com/manhua-zuiqiangzhirenzhuanshengcheng-f-jimaoxianzhe/

Start analyzing https://www.manhuaren.com/manhua-zuiqiangzhirenzhuanshengcheng-f-jimaoxianzhe/
Analyzing success!
已加入圖書館︰最强之人转生成F级冒险者
Start download 最强之人转生成F级冒险者
Start downloading 最强之人转生成F级冒险者
total 7 episode.
Downloading ep 第1话
Downloading 第1话 page 1: https://manhua1033-104-250-139-219.cdndm5.com/55/54044/913429/1_5284.jpg?cid=913429&key=ef9328b98bb8f506c2b03332b70e8447&type=1

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='manhua1033-104-250-139-219.cdndm5.com', port=443): Max retries exceeded with url: /55/54044/913429/1_5284.jpg?cid=913429&key=ef9328b98bb8f506c2b03332b70e8447&type=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 323, in error_loop
    process()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 296, in download
    crawler.download_image()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\crawler.py", line 81, in download_image
    self.image.url, referer=self.ep.current_url)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\module_grabber.py", line 27, in img
    **kwargs
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\grabber.py", line 208, in grabimg
    return ImgResult(grabber(*args, **kwargs))
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\grabber.py", line 105, in grabber
    r = await_(do_request, s, url, proxies, retry, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 905, in wrapped
    return f(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 927, in await_
    return async_(callback, *args, **kwargs).get()
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 682, in get
    raise err
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\worker\__init__.py", line 474, in wrap_worker
    self.ret = self.worker(*args, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\comiccrawler\grabber.py", line 119, in do_request
    proxies=proxies, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\ithildin\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='manhua1033-104-250-139-219.cdndm5.com', port=443): Max retries exceeded with url: /55/54044/913429/1_5284.jpg?cid=913429&key=ef9328b98bb8f506c2b03332b70e8447&type=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
Stop downloading
停止下載
Session saved

**Comment by IthildinX** [comment] 2019-11-03 05:05
手動點連結發現他圖源好像偷DM5的，然後就發生類似的錯誤了......

**Comment by eight04** [comment] 2019-11-03 11:38
Duplicate of #210.

**Closed by eight04** 2019-11-03 11:38 UTC
